/*
 * Decompiled with CFR 0.152.
 */
package com.pedrojm96.playeroptions;

import com.pedrojm96.playeroptions.CoreConfig;

public class AllString {
    public static String prefix;
    public static String no_console;
    public static String no_permission;
    public static String command_use;
    public static String description_use;
    public static String config_loaded;
    public static String command_error;
    public static String player_stacker_disabled;
    public static String player_pvp_disabled;
    public static String you_stacker_disabled;
    public static String you_pvp_disabled;
    public static String chat_disabled;
    public static String no_permission_speed;
    public static String no_permission_jump;
    public static String no_permission_doublejump;
    public static String no_permission_fly;
    public static String no_permission_stacker;
    public static String no_permission_visibility;
    public static String no_permission_chat;
    public static String no_permission_radio;
    public static String no_permission_pvp;
    public static String no_world;
    public static String command_speed_enable;
    public static String command_speed_disabled;
    public static String command_jump_enable;
    public static String command_jump_disabled;
    public static String command_doublejump_enable;
    public static String command_doublejump_disabled;
    public static String command_fly_enable;
    public static String command_fly_disabled;
    public static String command_stacker_enable;
    public static String command_stacker_disabled;
    public static String command_visibility_enable;
    public static String command_visibility_disabled;
    public static String command_chat_enable;
    public static String command_chat_disabled;
    public static String command_radio_enable;
    public static String command_radio_disabled;
    public static String command_pvp_enable;
    public static String command_pvp_disabled;
    public static String enabled;
    public static String disabled;
    public static String help_command_reload;
    public static String help_description_reload;
    public static String help_command_options;
    public static String help_description_options;
    public static String help_command_jump;
    public static String help_description_jump;
    public static String help_command_speed;
    public static String help_description_speed;
    public static String help_command_doublejump;
    public static String help_description_doublejump;
    public static String help_command_fly;
    public static String help_description_fly;
    public static String help_command_stacker;
    public static String help_description_stacker;
    public static String help_command_visibility;
    public static String help_description_visibility;
    public static String help_command_chat;
    public static String help_description_chat;
    public static String help_command_radio;
    public static String help_description_radio;
    public static String help_command_pvp;
    public static String help_description_pvp;

    public static void load(CoreConfig config, CoreConfig messages) {
        prefix = config.getString("prefix");
        no_console = messages.getString("no-console");
        no_permission = messages.getString("no-permission");
        command_use = messages.getString("command-use");
        description_use = messages.getString("description-usee");
        config_loaded = messages.getString("config-loaded");
        help_command_reload = messages.getString("help-command-reload");
        help_description_reload = messages.getString("help-description-reload");
        command_error = messages.getString("command-error");
        player_stacker_disabled = messages.getString("player-stacker-disabled");
        player_pvp_disabled = messages.getString("player-pvp-disabled");
        you_stacker_disabled = messages.getString("you-stacker-disabled");
        you_pvp_disabled = messages.getString("you-pvp-disabled");
        chat_disabled = messages.getString("chat-disabled");
        no_permission_speed = messages.getString("no-permission-speed");
        no_permission_jump = messages.getString("no-permission-jump");
        no_permission_doublejump = messages.getString("no-permission-doublejump");
        no_permission_fly = messages.getString("no-permission-fly");
        no_permission_stacker = messages.getString("no-permission-stacker");
        no_permission_visibility = messages.getString("no-permission-visibility");
        no_permission_chat = messages.getString("no-permission-chat");
        no_permission_radio = messages.getString("no-permission-radio");
        no_permission_pvp = messages.getString("no-permission-pvp");
        no_world = messages.getString("no-world");
        command_speed_enable = messages.getString("command-speed-enable");
        command_speed_disabled = messages.getString("command-speed-disabled");
        command_jump_enable = messages.getString("command-jump-enable");
        command_jump_disabled = messages.getString("command-jump-disabled");
        command_doublejump_enable = messages.getString("command-doublejump-enable");
        command_doublejump_disabled = messages.getString("command-doublejump-disabled");
        command_fly_enable = messages.getString("command-fly-enable");
        command_fly_disabled = messages.getString("command-fly-disabled");
        command_stacker_enable = messages.getString("command-stacker-enable");
        command_stacker_disabled = messages.getString("command-stacker-disabled");
        command_visibility_enable = messages.getString("command-visibility-enable");
        command_visibility_disabled = messages.getString("command-visibility-disabled");
        command_chat_enable = messages.getString("command-chat-enable");
        command_chat_disabled = messages.getString("command-chat-disabled");
        command_radio_enable = messages.getString("command-radio-enable");
        command_radio_disabled = messages.getString("command-radio-disabled");
        command_pvp_enable = messages.getString("command-pvp-enable");
        command_pvp_disabled = messages.getString("command-pvp-disabled");
        enabled = messages.getString("enabled");
        disabled = messages.getString("disabled");
        help_command_options = messages.getString("help-command-options");
        help_description_options = messages.getString("help-description-options");
        help_command_jump = messages.getString("help-command-jump");
        help_description_jump = messages.getString("help-description-jump");
        help_command_speed = messages.getString("help-command-speed");
        help_description_speed = messages.getString("help-description-speed");
        help_command_doublejump = messages.getString("help-command-doublejump");
        help_description_doublejump = messages.getString("help-description-doublejump");
        help_command_fly = messages.getString("help-command-fly");
        help_description_fly = messages.getString("help-description-fly");
        help_command_stacker = messages.getString("help-command-stacker");
        help_description_stacker = messages.getString("help-description-stacker");
        help_command_visibility = messages.getString("help-command-visibility");
        help_description_visibility = messages.getString("help-description-visibility");
        help_command_chat = messages.getString("help-command-chat");
        help_description_chat = messages.getString("help-description-chat");
        help_command_radio = messages.getString("help-command-radio");
        help_description_radio = messages.getString("help-description-radio");
        help_command_pvp = messages.getString("help-command-pvp");
        help_description_pvp = messages.getString("help-description-pvp");
    }
}

